defaultPlacement: end
enableVersioning: true
handle: events
name: Events
propagationMethod: all
siteSettings:
  f399f771-94d2-4947-b646-5167ef3e7739: # DIG Conference
    enabledByDefault: true
    hasUrls: true
    template: events/_entry
    uriFormat: 'events/{slug}'
type: channel
