defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  f399f771-94d2-4947-b646-5167ef3e7739: # DIG Conference
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
